---
- name: Req2
  hosts: R1
  gather_facts: false
  connection: network_cli
 
  tasks:
   - name: Load new ACL into device
     ios_config:
       parents: ip access-list extended REQ2 
       lines:
         - permit icmp host 192.168.20.20 host 192.168.10.10  echo 
         - permit icmp host 192.168.20.20 any echo-reply
         - deny icmp any any echo
         - permit ip any any  
                  
   - name: Apply new ACL to R1 Eth0/0.20 in
     ios_config:
       parents: int eth0/0.20
       lines:
         - ip access-group REQ2 in

   - name: Check result
     ios_command:
       commands: sh ip access-lists REQ2
     register: result
     tags: show

   - name: Print result
     debug:
       var: result.stdout_lines
     tags: show
