---
- name: Req3
  hosts: R1
  gather_facts: false
  connection: network_cli
 
  tasks:
   - name: Load new ACL into device
     ios_config:
       parents: ip access list extended REQ3 
       lines:
         - permit tcp 192.168.20.20 0.0.0.255 host 192.168.10.10  echo-reply 
         - permit icmp 192.168.20.20 0.0.0.255 any echo-reply
         - permit icmp any any echo-reply
                  
   - name: Apply new ACL to R1 Eth0/1
     ios_config:
       parents: int e0/1
       lines:
         - ip access-group REQ2 out

   - name: Check result
     ios_command:
       commands: sh access-lists
     register: result
     tags: show

   - name: Print result
     debug:
       var: result.stdout_lines
     tags: show
